language: d

d:
  - dmd
#  - ldc  # this causes valgrind internal error, and gets segmentation fault.

install:
  - |
    sudo apt-get -y update
    sudo apt-get -y install valgrind

script:
  - valgrind --tool=none -q --trace-children=yes --log-file=/dev/null dub test --compiler=${DC}
